FROM nginx:stable-alpine

COPY templates/index.html /usr/share/nginx/html/index.html
COPY static /usr/share/nginx/html/static

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 10001

CMD ["nginx", "-g", "daemon off;"]
