services:
  dellguardian:
    build: .
    container_name: dellguardian
    network_mode: host
    privileged: true
    restart: always
    environment:
      - PORT=5051
      - DELL_GUARDIAN_PASSWORD=hari1234
      - DELL_GUARDIAN_HOSTNAME=Dell M380
      - DELL_GUARDIAN_IP=192.168.13.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sbin:/sbin
      - /usr/sbin:/usr/sbin
