version: "3.8"

services:
  dellguardian:
    build: .
    container_name: dellguardian
    network_mode: host
    privileged: true
    restart: always
    volumes:
      - /sbin:/sbin
      - /bin:/bin
      - /usr/sbin:/usr/sbin
      - /usr/bin:/usr/bin